git clone git@github.com:GoodEnoughSocial/Sphere.Accounts.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Administration.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.ApiGateway.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Auth.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Branding.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Health.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Media.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Messages.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Profiles.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Relationships.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Shared.git
git clone git@github.com:GoodEnoughSocial/Sphere.Spheres.API.git
git clone git@github.com:GoodEnoughSocial/Sphere.Timeline.API.git

move .\Sphere.Accounts.API ..\
move .\Sphere.Administration.API ..\
move .\Sphere.ApiGateway.API ..\
move .\Sphere.Auth.API ..\
move .\Sphere.Branding.API ..\
move .\Sphere.Health.API ..\
move .\Sphere.Media.API ..\
move .\Sphere.Messages.API ..\
move .\Sphere.Profiles.API ..\
move .\Sphere.Relationships.API ..\
move .\Sphere.Shared ..\
move .\Sphere.Spheres.API ..\
move .\Sphere.Timeline.API ..\

copy .\pullall.bat ..\
copy .\Sphere.sln ..\
copy .\Directory.Build.Props ..\
copy .\.editorconfig ..\
copy .\.gitignore ..\
copy .\.dockerignore ..\