services:
  zookeeper01:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    environment:
      ZOO_MY_ID: 1

  kafka01:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper01
    ports:
      - 9094:9094
      - 9092:9092
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper01:2181"
      - KAFKA_BROKER_ID=1
      - "KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094"
      - "KAFKA_ADVERTISED_LISTENERS:INSIDE://:9092,OUTSIDE://:9094"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false

      # - KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      - JMX_PORT=1099